#!/bin/sh

# build/bin/dgalerkin doc/config/Cube.conf
# build/bin/dgalerkin  doc/config/Sphere.conf
# build/bin/dgalerkin  doc/config/Urban_3D.conf
# build/bin/dgalerkin  doc/config/land.conf

# build/bin/dgalerkin doc/config/Square.conf

build/bin/dgalerkin doc/config/Square.json